### ISSUE TITLE
Token Economics Discussion

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#172]
Let's talk about token economics! What are possible high-level models we can set up that will incentivize the behavior we are looking for?

I would like to see people propose ideas and then have those ideas considered and critiqued. And I would like to have a place to share my own thoughts.

**Comment by nick** [comment]
We should use tokens to incentivize good behavior, reward early adopters, etc... but how does that translate to the UI and how do we easily explain how it works to users who may be unfamiliar with crypto concepts? 

I think reward points is a good way to think about it... you simply get points (tokens) for good actions, and lose them for bad. Points for signing up, points for creating your first listing, points for writing reviews, referring friends, etc. Though of course putting in place protections from those who may game the system.

I know the idea of staking tokens has been considered... but how does that look to users? Perhaps this can simply happen under the hood... whenever you create a listing you automatically stake 10% of your remaining tokens. If you misbehave.. you lose them.

**Comment by dobbs** [comment]
At EthDenver I learned about Token Curated Registries in a talk by Mike Goldin.  Seems like they might be a good fit for maintaining a trusted registry for contracts (see also: https://github.com/OriginProtocol/origin-js/issues/159)

https://github.com/skmgoldin/tcr
[Token-Curated Registries 1.0](https://medium.com/@ilovebagels/token-curated-registries-1-0-61a232f8dac7)
[Token-Curated Registries 1.1, 2.0](https://medium.com/@ilovebagels/token-curated-registries-1-1-2-0-tcrs-new-theory-and-dev-updates-34c9f079f33d)
[A Closer Look at TCR 1.1 and the µ Equation](https://medium.com/@eamunoz.me/a-closer-look-at-tcr-1-1-and-the-%C2%B5-equation-7eafad6e882e)

**Comment by DanielVF** [comment]
I'm thinking that the reward/penalty for participants isn't just the token - you could have external stuff at stake as well. For example, getting listed could get you X dollars of new sales, or a few stores could collude ("invest") to get any new competitors from getting on the list.

That's TCR playground is fun!  Nice work!

**Comment by nick** [comment]
Yea the playground is awesome! How might the methodology apply to Origin listings?

One idea I had after looking at the playground:

Sellers stake tokens when creating their listing. 
Marketplaces built on Origin get either all or some of these tokens after a successful sale (commission).

- To use Stan's example, lets say I want to sell my bike and I put up a listing with 10 origin tokens staked.
- The bike isn't sold quickly due to lack of exposure.
- A budding entrepreneur sees lots of bike listings in Origin with significant tokens staked.
- They create a new marketplace built on Origin called block-bikes and promote it. Using their UI comes at a 'cost' of, for example, 50% of the staked listing tokens.
- Buyers start making purchases and block-bikes get 50% of the staked tokens for every sale they make. The rest of the tokens go to the buyer (like reward points).
- As the network and Origin token increases in value, early adopters are rewarded.
- The cost in Origin token to create a listing remains constant in fiat currency, eg $5. This can be seen as a commission of sorts. If someone really wants to sell their item quick, they might stake $50 of Origin token. If this is a job listing, it could be $1,000's (recruiters charge a lot :-)). Some marketplaces may only bother showing listings with significant Origin token staked.
- Marketplaces are incentivized to sell the listing first, as the first to do so gets the reward. This incentivizes marketplace efficiency.

This way the cost to create a listing remains relatively constant in fiat, eg $5, but as incentives (commissions) are priced in Origin token, early adopters are rewarded as the value of Origin goes up.

**Comment by tyleryasaka** [comment]
@nick Not yet sure how TCR would apply to Origin, or if it will end up being used at all. But I could certainly imagine listings being placed on a token-curated registry, either as a way to filter out bad listings or a way to highlight high quality listings (maybe like "featured" listings).

@nick Interesting idea. I'm not entirely sure I follow all the details, and I am not sure I understand the idea of people receiving a percentage of someone else's stake. Using your example, does that mean that the marketplace gets 50% when the bike sells? When it doesn't sell? When it gets listed? The idea of stake in my mind is that the staker gets 100% of their stake back unless they get rejected. It's like saying, "I'm this confident in my listing" (like placing a bet). So to me the stake always goes back to the staker, or to the people who challenged or bet against the staker. I'm not sure what scenario it would make sense or be fair to award a stake to a 3rd party. And if we're just talking about a more general fee for being listed on a marketplace - well, that seems to contradict the Origin model of removing middlemen that charge fees.

**Comment by nick** [comment]
I guess I meant 'bounty' instead of 'stake' in this context (although we'll need a stake too). The way I see it, the primary function of Origin token is to act as an incentive mechanism for sellers to get their items sold quickly and efficiently. In order for this to happen, marketplace apps will need to be built - but that wont happen unless there is a financial incentive to do so.

Although the stated goal of Origin is to 'remove middlemen that charge fees', I don't see how that is practical as there is no financial incentive for developers to spend months or years building a new marketplace on top of Origin. Rather, I think the stated goal should be to 'drastically reduce fees' while removing the data monopoly that big players currently enjoy. 

Here's how the incentive mechanism for a home sharing marketplace built on Origin could work. Lets imagine the market price of Origin token is $1 and the token identifier is OGN.

### Seller

Seller lists their property and indicates they are willing to pay a bounty of 5 OGN for every day booked. They also stake a further 50 OGN as proof that their listing is 'legit'. This stake can be depleted by any 'bad' actions the seller might take, such as cancelling a booking, not responding to booking requests, etc. So in total the seller puts up 100 OGN (50 OGN stake and 10 days * 5 OGN for booking bounties). This can be topped up with more OGN by the seller at any time. It can also be refunded at any time in full if the seller removes their listing.

### Marketplace

Marketplace apps need a financial incentive to exist, and the 'bounty' offered by sellers gives them an income from day 1. A marketplace app can offer different levels of service depending on the bounty offered by sellers. For example, a minimum bounty of 2 OGN/day may get you a basic listing, while 5 OGN/day will mean a promoted listing, plus email customer service.

This is kind of how Kayak / Expedia / Priceline etc work: earning a commission for fulfilling orders.

As marketplace apps compete to fulfill orders, the Origin ecosystem as a whole becomes more efficient. The barriers to entry are zero: anyone can spin up a new marketplace, immediately have all the data and users ready to go and start earning bounties.

### Buyer

Buyers will have a whole range of marketplaces to choose from. They may only choose marketplaces that offer good customer service, or more loyalty points (in the form of OGN). Switching marketplace is easy as they take their reputation and transaction history with them. Buyers can even use the default Origin app and get the whole OGN bounty for themselves.

### Incentives

If bounties are priced in fiat, marketplaces are still able to turn a profit while benefitting as the network grows and the value of OGN increases. The $5 in OGN you earn today could be worth $20 next year. Or, you could simply cash out now in order to fund operational costs.

The low barriers to entry will keep competition tight and middleman costs low. Sellers still have the option to list with a zero bounty... it'll just mean less exposure.

**Comment by nick** [comment]
I pushed my Marketplace playground code to help visualize these concepts to [this branch](https://github.com/OriginProtocol/identity-playground/tree/marketplace) on the identity playground repo, along with a [demo video](https://vimeo.com/277644767) showing how it works.

**Comment by micahalcorn** [comment]
I'm going to consider this done considering that we are seemingly ready to write code for a prototype. Feel free to continue the discussion here if appropriate.

**Comment by lucadgtrip** [comment]
> Seller lists their property and indicates they are willing to pay a bounty of 5 OGN for every day booked. 

this is basically a commission and so it's fine with Hosts  psychology: everybody is happy to pay a fee only if they get a confirmed booking (Airbnb style), while it's really really hard to ask them to pay a significant fee upfront with no guarantee of bookings (Homeaway abandoned model).
The weak aspect seems to be that the 5 OGN a day will be too much for some properties (10 U$ a night hotel in Thailand) and too little to matter for some others (1000 U$ a night villa).
It may still work for the majority of listings tough but we need to consider that it won't work for the others.

> They also stake a further 50 OGN as proof that their listing is 'legit'. This stake can be depleted by any 'bad' actions the seller might take, such as cancelling a booking, not responding to booking requests, etc.

that makes sense but the marketplace must be clear very clear upfront about what "legit" is and who decides about bad behaviour. 

I have to admit it's not 100% clear to me if this is optional and adjustable for the marketplace or forced?
