### ISSUE TITLE
Docker: Docker Compose instead of a single container running pm2?

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-js#229]
Right now we have a single Docker container that manages multiple processes using node [pm2](http://pm2.keymetrics.io/). This may be just fine, but I wanted to put up an alternative for discussion. [Docker Compose](https://docs.docker.com/compose/overview/) can be used to manage multiple containers at once, and each container could then manage one process. I don't have a strong opinion on this, but maybe something to think about.

**Comment by marcogbarcellos** [comment]
I've heard some opinions about the "Origin Box" and was looking into the docker files you have today, (this folder)[https://github.com/OriginProtocol/origin-js/tree/develop/bridge-container] could be called docker folder and you guys could use Docker Compose to simplify things: make the bridge Dockerfile lighter using only itself inside its Dockerfile and create a docker-compose file to link the dependency it needs(redis, postgresql, elasticsearch, etc). you could also could optionally do the same with the origin dapp(perhaps there or even a separate tiny project might be a better place to create the origin box). I'm sorry if some of these things don't  make a lot of sense, I'm still studying how the origin parts communicate and depend on each other.

**Comment by ambertch** [comment]
Hi Marco, check out https://github.com/OriginProtocol/origin-box

**Comment by tomlinton** [comment]
I'm in favour of using just docker-compose. I built a development environment based on that which I use and others might find useful: https://github.com/tomlinton/origin-develop.

I think it has a lot of advantages (but also a few disadvantages):

- pm2 doesn't add anything over docker-compose if you think of each container as one process, and it is one more thing people have to learn to get up and running
- easy to switch out components, e.g. I was testing python 3.7 compatability with origin-bridge and it just requires a single line change and a rebuild of only the origin-bridge container rather than a rebuild of the complete stack
- logs are heaps easier to read and manage
- you can spin up only what you need, e.g. `docker-compose up origin-js` if you just want origin-js, `docker-compose up origin-bridge` for origin-bridge, or just `docker-compose up` for everything, dependent containers will start automatically
- uses docker official repositories so it is a lot quicker to get a stack up and running

Package management is a little tricker in my setup because packages are installed during container builds rather than when the containers are run. Same with database migrations. That doesn't really relate to docker-compose though, it is just how I've set things up.

**Comment by franckc** [comment]
Thanks for sending this proof of concept for Docker Compose @tomlinton !

Since most developers run Docker on their laptop/desktop, one question I have is regarding host resources consumption (in particular RAM). Based on your testing on your prototype, does Docker Compose use less/more/equivalent RAM than our current pm2 based setup ?

**Comment by tomlinton** [comment]
It'll definitely use more because the virtualisation done by docker has to happen once for each container and I'm running 7 separate containers. According to `docker stats --all` they are using about 1gb of RAM total. I'd guess origin-box would use 100-200mb less than that. I don't think it'd be noticeable on most modernish laptops.

**Comment by DanielVF** [comment]
Currently the origin-box just seems to work for me, every time. I love it! My main concern is stability and just-working-ness. How stable is docker-compose?

**Comment by tomlinton** [comment]
I use it day to day and it is stable for me, but I'm sure things would pop up if others used it. Incompatibilities in the develop branches between the three components may cause issues, but that isn't really related to the use of docker-compose. The container build process should be more stable than origin-box because of the use of official docker repos for services like postgresql and redis.

**Comment by franckc** [comment]
@ambertch any thoughts on this topic since you originally implemented origin-box ? :)

**Comment by tyleryasaka** [comment]
I will say that I am very happy with the current setup with pm2. I'll also mention that pm2 actually built this tool specifically for docker, so it's not a hack or anything. http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/

What I like about pm2 is that I can go into the box terminal and easily start and stop processes with simple commands. And can also watch logs for specific processes.

- `pm2 start js`
- `pm2 restart js`
- `pm2 stop celery`
- `pm2 logs bridge`

...And so forth. Very convenient.

If docker-compose made this more difficult, I probably would get pretty frustrated. I'd also be curious what practical improvements it would add over our current setup.

**Comment by tomlinton** [comment]
Consider these commands (I named things a bit differently, e.g. origin-js instead of just js):

- docker-compose up origin-js
- docker-compose restart origin-js
- docker-compose stop origin-bridge-celery
- docker-compose logs origin-bridge

The pm2 approach is less convenient because you have to spawn a shell in the container to run those commands. Additionally pm2 has no concept of dependencies, `docker-compose start origin-bridge` will start origin-bridge and automatically start any dependencies (postgresql, redis, origin-js). I see pm2 as only adding complexity and an extra thing for new developers to learn. From that link it looks like pm2 may have advantages for node applications, but at this stage we are not using them, and if we want them later we just add pm2 to the node based containers and not use it to run the whole stack.

I understand that it is annoying relearning how to use a development setup and it'll slow you down. The aim of the setup I built was to provide a better experience for new developers (I had an advantage here because I was new to the project). It does offer practical improvements for people already using origin-box though, I'll give two examples:

**Tests**

Stan pointed this one out in discord yesterday. If you want to test origin-js you have to bring down origin-js, run the tests, then bring origin-js up again because of a port conflict. The docker-compose setup runs the tests in an isolated container with a single command so you can keep your stack running.

Personally thats almost a compelling enough reason on its own to use the docker-compose setup. I don't want to be stopping and starting origin-js to run tests for the rest of my days.

**Maintainability**

There is an open issue on origin-box to upgrade to postgresql 10, this is what the process would be:
- Edit [these lines](https://github.com/OriginProtocol/origin-box/blob/69c30dc3c96ddb0cdf4622b93a84f4f5e544f122/container/Dockerfile#L17-L30) to make sure postgresql 10 is being installed
- Edit pg_hba.conf to make sure it conforms to any changes for postgresql 10
- Edit postgresql.conf to make sure it confirms to any changes for postgresql 10
- Edit this [start script](https://github.com/OriginProtocol/origin-box/blob/master/container/files/scripts/start-pg.sh) to make postgresql 10 start instead of 9.3
- Rebuild the container, which necessary involves rebuilding everything (this takes around 10 minutes, I haven't timed it, just a guesstimate)
- Restart

With the docker-compose setup:

- Change [this line](https://github.com/tomlinton/origin-develop/blob/f7524a27644e85dd74f3702ecf78c8fd140afb5b/docker-compose.yml#L16) from postgres:9.3 to postgres:10.0 (it is done already)
- Restart

Want to test things on python 3.7? The procedures are similar.

I encourage you to give it a try, I'll be around in discord if you have any issues. I'll keep maintaining the docker-compose setup while I'm contributing because I use it. My setup is definitely not perfect and people using it are bound to run into issues that I haven't (yet), but I think there are definite upsides.

**Comment by ambertch** [comment]
When I was putting together the development container, not having used docker-compose before, I was thinking it was equivalent to Kubernetes in complexity (in development mode, Kubernetes is run off of Virtual Box, and it also has component services for service management, data store, and API)... it looks like docker-compose is less heavyweight.

I think that if we were starting from scratch with the components we have now, docker-compose might offer a good amount of flexibility, @tomlinton makes some good points. In addition to running tests and maintainability, various parts of the stack might be run locally vs. remotely. For instance, say we wanted to simulate multiple dapp vendors or bridge server-like components operating on the same blockchain: all the components could be pointed to the local environment, with the shared blockchain operating in a remote staging environment.

A hypothetical use case might be if we start experimenting with Plasma or other state channel / layer 2 devices, since there might be a remote main chain and more ephemeral side chains existing in development environments.

That being said, besides reseting state to run tests, it does seem like the current containerized setup works well. In-box processes can be shut off if the scenario requires it, and many people on the team are used to running that environment.

My guess is that as time goes on, as more filed or requested changes to the box are made, there will be more reasons to build a setup using docker-compose and/or convert the environment to be microservices based.

**Comment by tyleryasaka** [comment]
@tomlinton I'm not attached to the current setup, just was pointing out that it seems to be working (relatively) well. Granted, my frame of reference is that I used to have to run and maintain all 3 repos separately on my own machine.

One note on the tests - I'm pretty sure we can easily reconfigure the tests in origin-js to run on different ports. Trivial fix that I just never got around to.

That said you make a compelling argument for docker-compose. Can you open a pull request to this repo? Based on your description it seems great to me.

**Comment by tomlinton** [comment]
@tyleryaska you are right, I was being way too dramatic there. :blush: We could fix it up easy.

Do you mean a pull request to origin-box? This issue is on the wrong repo. My setup is a rewrite so it doesn't share any code with origin-box. I could put it on a branch though so people can try it?

**Comment by franckc** [comment]
+1 for putting this on a branch on the origin-box repo then people can try it and, assuming no blocker, we can merge it to make this the default origin-box setup.

**Comment by ahaidery** [comment]
Hey guys, new here! Would love to be able to tackle this and come up with a sample docker-compose file if that's okay

**Comment by tomlinton** [comment]
Hi @ahaidery! This discussion was about a docker-compose setup that I put together. I just pushed it to a branch [here](https://github.com/OriginProtocol/origin-box/tree/compose). We'd be happy to have your contributions and thoughts on it. You might even be the first person to use it apart from me. :grin:

**Comment by ahaidery** [comment]
@tomlinton cool! would love to try it out and get back to you with any feedback :+1:

**Comment by tyleryasaka** [comment]
@tomlinton Oh I see, yeah I meant the origin-box repo. I'll take a look at your implementation. 👍

**Comment by franckc** [comment]
I tried the docker-compose setup this week-end and it worked pretty well for me.
The install succeeded on my first try and the services were stable. Even though I am not familiar with docker-compose, it was fairly simple to figure out the commands I needed. 
After playing with the DApp, I made a few simple changes to run the Ganach UI on my host while the services were running in the containers and that worked well too.

So overall pretty happy with this docker-compose setup !

A few minor nits (I can add them as comment to the code if easier):
 - Add instruction in readme to start a bash into a container (e.g. something like :"docker exec -ti <container_name> /bin/bash -i" 
 - In README, to rebuild a container, command should be: "docker-compose build --no-cache origin-js" (the --no-cache option goes before the container name)
 - In install.sh , the DApp and bridge server ports are mixed up

**Comment by franckc** [comment]
One more piece of feedback: having the DApp and Bridge server config files in the origin box repo under origin-box/envfiles might cause those env files to get out of sync with the env files developers commit in origin-dapp and origin-bridge ?

We had ocurrences in the past where developers would add or remove keys from the dev.env files in the origin-bridge repo but would forget to do the same in the origin-box repo. As an attempt to minimize the chances of this occurring again, currently origin-box uses "box.env" envfiles that are checked in under the origin-bridge and origin-dapp. See for ex. https://github.com/OriginProtocol/origin-bridge/blob/develop/box.env Reasoning being the developers are more likely to notice that box.env file and update it if it is sitting in the same repo as the dev.env file they modify.

**Comment by tyleryasaka** [comment]
I'm really liking this @tomlinton . Works great for me! I'll try doing some development with it and see if I have any thoughts.

**Comment by franckc** [comment]
Couple more things:
 - I find myself sometime editing some src files of env files from within the container. By default it does not look like the ubuntu image includes any text editor. I work around this by running "apt-get install vim" from within the container. Might be nice to install a basic editor like vi or nano.
 - ElasticSearch container is commented out - would be nice to have that though can be done as separate PR once we decide docker-compose is the way to go.

**Comment by tomlinton** [comment]
Glad to hear its working out @tyleryasaka!

- Yep gotcha. This relates to the above issue about where we keep the env files. There is a bit of a trick with how this will have to be setup. We'll have to use volumes so that env files persist across containers (e.g. the origin-bridge-celery env file should be the same as origin-bridge). Easy enough to do!
- Not a problem. It was working fine but I just commented it out because of the log spam it produces. I was going to look into a way to decrease the amount of information it logs.

**Comment by tomlinton** [comment]
I had a thought regarding env files. What if we remove them from origin-bridge and origin-dapp? If all development happens in the origin-box environment they only need to be included here. If everyone uses origin-box then:

- It is easier to provide support/troubleshoot any issues for developers
- Origin-box will become a better project through more use

The env files in origin-box will stay up to date because during reviews of pull requests other developers will be using origin-box to test and it'll be easy to spot if someone forgot to update them. It also removes the need to connect directly to containers to modify env files.

The downside would be that we are making everyone do development in a specific way. If someone really wants to run the projects without docker-compose it wouldn't be too hard to figure out though.

**Comment by franckc** [comment]
Yes, if origin-box is the primary development environment we support/recommend, then imho would be ok to put all env files there for simplicity. Then we can update README on other repos to point to those env files.

**Comment by franckc** [comment]
One issue I have with my setup is that when I update a JS file in the DApp repo, it does not get detected and does not rebuild the DApp automatically. I have to explicitly restart the service (e.g. "docker-compose restart origin-dapp).

I checked and dockerfiles/origin-dapp does have NODE_ENV set to "development" so not sure what the issue is ?

**Comment by micahalcorn** [comment]
We do want to continue to support running the repos independently since Docker requires registration, but linking people to env files might be acceptable. @wanderingstan?

**Comment by tomlinton** [comment]
@franckc that is strange! I tested it out now and had no issue. Which file are you editing? I did have to rollback to a previous origin-dapp commit on the develop branch because it wasn't compiling at all due to some recent changes. If you watch the log outputs (`docker-compose logs -f origin-dapp`) you should see webpack trigger a recompilation on any file change, it might be that the compile fails so the changes aren't reflected in the browser. The only other thing I can think of is if you are not in the origin-box/origin-dapp directory and are using a different copy of origin-dapp. (I have done this :grin:).

I'm not registered for Docker as far as I know, I do remember some fuss a while ago about them requiring registrations though. Maybe just for uploading images to Docker Hub? Will have to look into it.

**Comment by franckc** [comment]
@tomlinton Did a few more tests:
 - issue is not specific to origin-dapp repo. I have sthe ame problem with origin-js and origin-bridge
 - when I modify a file from within a container (I spawn a batch then use vi), the change gets detected and a recompile kicks-in
 - when I modify the file from my host, the file content is changed on both host and in container but no recompile happens. so it looks as if the file-system event don't make it into the container...

I'm running Docker 8.06.0-ce-mac70 on a MacOS 10.13.6

**Comment by franckc** [comment]
@tomlinton Did a few more tests:
 - issue is not specific to origin-dapp repo. I have sthe ame problem with origin-js and origin-bridge
 - when I modify a file from within a container (I spawn a batch then use vi), the change gets detected and a recompile kicks-in
 - when I modify the file from my host, the file content is changed on both host and in container but no recompile happens. so it looks as if the file-system event don't make it into the container...

I'm running Docker 8.06.0-ce-mac70 on a MacOS 10.13.6

**Comment by tomlinton** [comment]
Thanks @franckc looks like it is [this issue](https://github.com/docker/for-mac/issues/681). I never tested this on OS X. I'll see if I can implement a work around for it.

**Comment by tomlinton** [comment]
@franckc I tried a few things on OS X to reproduce (bringing the containers up/down and using docker-compose restart, vim and atom for editors) but couldn't get it to happen. Seems like a very annoying issue though. Anyone else experiencing it?

**Comment by micahalcorn** [comment]
Just a comment that my clean installation and setup took what seemed like a really long time. It certainly felt noticeably longer than the non-compose version, but I didn't think to time it. When it comes to alleviating developer frustration, we should also consider the possibility than many machines may not have the memory capacity to run this environment. Is that more or less of a concern with compose?

**Comment by ahaidery19** [comment]
@micahalcorn it makes sense that it would take longer than usual to stand up the environment for the first time since docker needs to download the corresponding images. Is it taking just as long to stand up the environment each subsequent time as well? Should be faster since the images are downloaded.

**Comment by tomlinton** [comment]
@micahalcorn It should be significantly faster with docker-compose. This method does a lot of downloading so it is mainly dependent on your network. Without docker-compose it is CPU bound, it does a lot more compiling. I'll time both from a clean install today and see how it looks.

Regarding memory usage, I discussed it a bit above. It uses more this way, but probably only by around 20-30%. I'll put together some measurements on this too.

**Comment by micahalcorn** [comment]
@tomlinton thanks, sorry I missed that. I skimmed through and searched "memory" but not "RAM". 🤦‍♂️

**Comment by tomlinton** [comment]
I benchmarked the builds with `time docker-compose build --no-cache` and cleared out everything in between with `docker system prune -a` and `docker volume prune`. I did it on two platforms. I didn't put the exact specs of the machines here but they aren't really needed as it is just for comparison. Here are the numbers:

**Linux** (Dell XPS 15)
compose branch - 5:05.02
master branch - 9:03.84

**OS X** (Macbook Pro 2015)
compose branch - 7:24.08
master branch - 9:46.31

So docker-compose is a fair bit faster in both cases, nearly twice as fast on the Linux test. It might have felt slow but that is possibly because you wouldn't have rebuilt your origin-box container from scratch for a long time. I'm sure we could optimize here and speed things up, but it is a one off process anyway. Some of the stuff that is done at run time in the master repo like `npm install:dev` is done in the build step with the compose repo, so the compose repo should have a faster startup time once everything is built.

Also checked out memory usage using docker `docker stats --all --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}"`: The compose branch came in at ~1.55gb (sum of memory usage for all containers) and the master branch was 1.471gb (just the single container). It's less of a difference than I thought but `docker stats` might be a bit disingenuous as I'm not sure it accounts for the overhead of running more containers.

**Comment by tomlinton** [comment]
I think it is working well. Not sure if there are any other regular origin-box users who want to give it a go.

I'm a bit concerned about the issue @franckc mentioned. It's a bug in Docker for Mac that we don't have much control over. I couldn't reproduce though. Did you run into it at all @micahalcorn? We could raise it as an issue anyway.

Yep it would negate that. It looks like it would close all the open issues too.

**Comment by franckc** [comment]
Yes, I'm a bit worried about this issue I encountered. I'd be curious to see if anyone else encountered it.... @wanderingstan you tried the docker compose setup for the website. Were file changes you made from your host (for ex. while editing source code on your Mac) detected in the container and caused automatic recompilation of the stack ?

**Comment by tomlinton** [comment]
@wanderingstan that issue you pointed out in Discord with flask-recaptcha should be fixed. Just pull the latest changes and run `install.sh -e origin-website` again. 

@franckc you never experienced this issue with the `master` branch? From the looks of the issue thread it is caused by volumes and the `master` branch has them as well. If you were working inside the container you'd never run into it though.

**Comment by franckc** [comment]
@tomlinton A few more data points:
 - I downloaded Docker from docker.com - it is version 18.06.0-ce-mac70 (26399)
 - When I was having the issue on compose branch, the master branch was working fine
 - I just rebooted my Mac and now things are working fine for me on compose... !

Let me continue using compose over the week-end and see if I can reproduce the issue.

**Comment by wanderingstan** [comment]
@tomlinton - It's working! Awesome. 🎉 Thanks for the clearly documented steps. 

@franckc - Yes, it appears to detect local changes. I edited some text on the homepage and it was automatically there when I reloaded the page.

**Comment by franckc** [comment]
Following up: my compose setup was stable over the week-end after I rebooted my laptop on Fri. So maybe the bug I encountered was just caused by some weird instabilities on my Mac ?  Anyway, given that nobody else had that issue, I think we can consider it is not blocking for moving forward.

If everyone is happy with docker compose, I'd suggest we make it our default origin-box setup by merging the "compose" branch into master. Any objections ?

**Comment by tyleryasaka** [comment]
So I spent a few hours today trying to get the `compose` branch to work. It's probably just something weird on my end, but my `origin-dapp` will not start properly. Some of the modules are apparently not being installed.

I tried rebuilding several times, including with the no-cache option. Same error every time.

If no one else is having this issue I'm fine with merging to master, but I am a bit confused why it's not working. It's hard to troubleshoot because I can't inspect the files in the container.

<img width="872" alt="screen shot 2018-08-05 at 5 01 28 pm" src="https://user-images.githubusercontent.com/6504519/43702553-f8be32d4-990e-11e8-9c79-4c63c4276de4.png">

**Comment by tomlinton** [comment]
@tyleryasaka I think you are missing #289 from your local copy of `origin-js`. The `origin-js`, `origin-dapp` and `origin-bridge` directories are placed directly in the containers so you can check out the files in there to debug. If you pull down the latest stuff on the develop branch in all three you should be fine, but let me know if not.

**Comment by tomlinton** [comment]
Actually more likely the [corresponding PR](https://github.com/OriginProtocol/origin-dapp/pull/325) from `origin-dapp` that you are missing. :grin:

**Comment by tyleryasaka** [comment]
@tomlinton I checked several times that I pulled the latest changes from `develop` when troubleshooting, so I don't think that was the issue. And yeah I realize the files are synced between local filesystem and container, I just wanted to check the node_modules directory inside the container (which is not synced).

I will keep troubleshooting though. Thanks!

**Comment by tomlinton** [comment]
I have seen those errors before, but I can't remember how I fixed it. :disappointed: Here are some things that might help debugging though:

- The origin-js `node_modules` folder is a volume. Run `docker volume ls` and you should see a volume called `origin-box_origin_js_node_modules`. You can then run `docker volume inspect origin-box_origin_js_node_modules` and it'll show you the path to it on your local machine next to "Mountpoint". Unfortunately the origin-dapp `node_modules` is not a named volume like this.
- Running `docker-compose down` followed by `docker system prune -a` and `docker volume prune` will give you completely fresh start. Then just rerun the install.sh.

Let me know if you figure it out so we can capture what caused it in the documentation and/or try and fix it.

**Comment by tyleryasaka** [comment]
Ok, finally got things working! I think some sort of caching was the culprit. Removed all my docker images and rebuilt everything from scratch, and that got it. Used https://stackoverflow.com/questions/46487684/docker-compose-cannot-find-new-node-module as a guide.

**Comment by tyleryasaka** [comment]
I created a PR to merge the `compose` branch to `master`. https://github.com/OriginProtocol/origin-box/pull/29

**Comment by tyleryasaka** [comment]
Completed by https://github.com/OriginProtocol/origin-box/pull/29
