### ISSUE TITLE
Marketplace Tests

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#351]
Since the contracts have been overhauled in favor of the marketplace contract, the tests should be updated to include the appropriate coverage and include verification that upgradability works as intended.

**Comment by tyleryasaka** [comment]
Making this my priority now

**Comment by nick** [comment]
There are some here, unfortunately not in the same format as everything else:

https://github.com/OriginProtocol/identity-playground/blob/marketplace/test/Marketplace.js

Could be an opportunity to move to instant running tests though 😬

**Comment by nick** [comment]
I have some Marketplace (and identity) tests written [here](https://github.com/OriginProtocol/identity-playground/blob/marketplace/test/) which we can use, unfortunately not in the same format as everything else. Perhaps this could be a good time to switch away from Truffle-style tests so we can benefit from instant running, watchable tests using vanilla mocha. The [test helper script](https://github.com/OriginProtocol/identity-playground/blob/marketplace/test/_helper.js) also includes a gas price watcher which is useful for monitoring prices as contracts change:

<img width="468" alt="screen shot 2018-08-18 at 1 15 46 pm" src="https://user-images.githubusercontent.com/939/44299235-1ac58780-a2ea-11e8-9327-2da77307da9b.png">

I know we had this discussion before and decided to stick with truffle for the time being, but I think this is a good opportunity to revisit the discussion as I already have a lot of tests written that we'd otherwise need to port.

**Comment by nick** [comment]
I pushed a branch [here](https://github.com/OriginProtocol/origin-js/tree/nick/issue-336) with all the marketplace tests from the playground. You can try them out with `npm install` followed by `npm run test:contracts-alt`

**Comment by cuongdo** [comment]
@nick I like instant reload of tests. 

How does live watching work for `npm run test:contracts-altw` though? I ran that on your branch then intentionally put in a syntax error in `v01/marketplace.sol`. I didn't see the error or the `solc` output I expect from the recompilation of the contract. In contrast, when I run `npm run test:contracts`, it recompiles upon any JS or Solidity change.

What's involved in porting tests from Truffle? Is it just porting tests from `web3` 0.20.x to some beta 1.0.0, or is there more?

**Comment by nick** [comment]
Right now it's only testing version v00 but we can run all the same tests for v01 too.

As discussed on discord, migrating truffle tests shouldn't be too difficult, mostly just using web3 1.0 syntax instead of truffle-contract syntax.

**Comment by cuongdo** [comment]
I like the speed of the plain Mocha tests. I'll defer to @tyleryasaka, as he's already working on tests.

**Comment by tyleryasaka** [comment]
Thanks @nick I'll be trying out the truffle-free tests

**Comment by tyleryasaka** [comment]
I'll be doing work on this branch: https://github.com/OriginProtocol/origin-js/tree/tyleryasaka/issue-351

@nick I moved your commit there, and out of the issue-336 branch (that's really dealing with something different).

**Comment by tyleryasaka** [comment]
Made progress toward this goal with https://github.com/OriginProtocol/origin-js/pull/380 (thanks to @nick 's helper and tests), though I think we should examine the tests some more before calling this done. Just to make sure we have sufficient coverage.

**Comment by micahalcorn** [comment]
Related: https://github.com/OriginProtocol/origin-js/issues/341 & https://github.com/OriginProtocol/origin-js/pull/393 & https://cuongdo.github.io/hacked_up_coverage/marketplace/v00/Marketplace.sol.html

**Comment by micahalcorn** [comment]
@tyleryasaka how are you feeling about this one now?

**Comment by micahalcorn** [comment]
Considering this done via #436 ✅
