### ISSUE TITLE
Circular dependency to make ClaimHolderPresigned correctly

### ISSUE THREAD

**Issue by victorwiebe** [OriginProtocol/origin-js#366]
https://github.com/OriginProtocol/origin-js/blob/0c09e12a823ae049906c84f66a8181b26ad96215/contracts/test/identity/TestClaimHolderPresigned.js#L21

Referencing: https://github.com/OriginProtocol/identity-playground/blob/0c9ba5c008d410e1ca82a2b1eed15705db49af0f/test/ClaimVerifier.js#L40

Hi there, 
I've been doing an integration of this protocol into a new ethereum project. Something I have noticed is that if you want to use ClaimHolderPresigned, it seems that theres a circular dependency here as to create a Claim on a contract, you create **var hashed = web3.utils.soliditySha3(UserIdentity._address, claimType, data)** 

But in the case of ClaimHolderPresigned, I am confused as you cannot take this route to create the signature hash that will be signed by this private key because it is dependent on the address UserIdentity._address which technically you are in the process of creating. In the unit tests, there is some hex data there that I am not sure if it is random or not.

Any clarification would be great as ClaimHolderPresigned is very confusing from this front. Tests pass here with random data in place of that hash, so I am trying to figure out what the best practice would be for generating **hashed** above

**Comment by victorwiebe** [comment]
@nick @tyleryasaka Would appreciate your response

**Comment by tyleryasaka** [comment]
@victorwiebe Great question.

The key here is realizing that a contract's address can be deterministically computed, before the contract is actually deployed: https://ethereum.stackexchange.com/a/761.

In origin-js we take advantage of this and have a function to actually compute this address right before we deploy the contract: https://github.com/OriginProtocol/origin-js/blob/master/src/resources/attestations.js#L188

As for why we are doing this: we want to minimize the number of transactions that the end user must perform. It's a UX optimization. Without the presigned contract, we would need 2 transactions. The first to deploy the contract, and the second to add attestations (because each attestation must include a signature of a message that includes the identity contract address).

It's a bit of a hack but the end result is that it allows us to reduce user friction.

**Comment by joshfraser** [comment]
@tyleryasaka great explanation & this is such a cool hack. We ought to write a blog post about it or something.
