### ISSUE TITLE
Migration of token approvals

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-js#388]
Currently, our [token contract](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/token/OriginToken.sol) does not support migration of approvals through `approve`, `increaseApproval`, and `decreaseApproval`. That's because all these methods rely on `msg.sender`, which makes migrations on behalf of other addresses impossible. This is problematic if any caller of the token contract depends on approvals.

It looks like there are two places our `Marketplace` contract depends on `transferFrom`:
1. https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v01/Marketplace.sol#L93
2. https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v01/Marketplace.sol#L108

This is just our code. I'm not clear on whether exchanges and anything else that interacts with tokens needs `transferFrom`.

@DanielVF @nick Please share your thoughts. If we do need this, I'd like to get this in soon to avoid needing a migration in the near future.

**Comment by nick** [comment]
I'm hoping we can avoid the need to migrate approvals as it'd likely mean more custom code that could possibly be construed as a backdoor.

Right now in order for a seller to stake Origin Tokens, they will first need to approve the Marketplace contract to transfer tokens on their behalf. Whenever we deploy a new Marketplace contract, they'd need to approve that new contract too (and possibly un-approve the old contract). We still need to discuss when and how the seller issues approvals and there are a few possibilities:

*1. Each time a new listing is posted we approve only the number of tokens the seller intends to stake*
**Pros**: Marketplace contract never has access to transfer more tokens than it needs. 
**Cons**: Seller would need to perform 2 transactions for every new listing

*2. Allow the seller to pre-approve a limited sum to be managed by the marketplace contract*
**Pros**: No need to approve a transfer for every new listing. 
**Cons**: Still need to approve sporadically

*3. Allow the seller to pre-approve an infinite sum to be managed by the marketplace contract*
**Pros**: No need to approve a transfer for every new listing. 
**Cons**: Still need to approve when marketplace contract is upgraded. Token balance could be compromised if a flaw is found in Marketplace contract.

My personal preference is for option 2, though we'll still need to work out the UI for it.

I think we only need approval migrations if we go with option 3, as otherwise the seller will likely have to approve more tokens at some point anyway.

**Comment by cuongdo** [comment]
@matthewliu: This is is a product discussion, so looping you in. We don't need to necessarily implement anything for v1 as long as we pick options 1 or 2. 

@nick I believe the latest thinking is that we're not implementing staking for v1. So, the main concern here is making sure the token contract code is feature complete for the foreseeable future.

I like option 2. A limited sum can still be enough to cover many listings, and it can later be made dynamic to match a seller's volume or preferences.

I also like having less custom code in the token contract, as long as we don't make large UX sacrifices.

**Comment by matthewliu** [comment]
@cuongdo @nick I'm still having a bit of trouble understanding this fully from a product perspective.

A. We don't need staking for sellers in v1, but should make sure we don't box ourselves in a corner.

B. I think I might be misunderstanding how the marketplace contract and desired staking work. When a seller stakes, aren't the tokens already "staked" and "controlled" by the marketplace contract? Are we saying that this is not the case and that we are just giving the marketplace contract the ability to transfer at a later date? Are the implications that whenever we make an update to a marketplace contract that all listings need to go through this same approval process (or that they they need to just use the old contract)?

C. I'm confused by option 1 listed above? Are the two transactions create listing and approve contract? Or is it approve listing and then transfer tokens for staking? Is it possible to do either one of these in a combined single step?

**Comment by nick** [comment]
*When a seller stakes, aren't the tokens already "staked" and "controlled" by the marketplace contract?*
Yes, but since it's the marketplace contract initiating the token transfer, the seller must first give it permission to do so.

*Are we saying that this is not the case and that we are just giving the marketplace contract the ability to transfer at a later date?*
Since the approval must happen in a separate transaction, approving enough tokens for multiple listings will save a step later on.

*Are the implications that whenever we make an update to a marketplace contract that all listings need to go through this same approval process*
The seller will need to go through the approval process if: a) if they want to create a listing on a new marketplace contract, b) if the token contract has been upgraded or c) if they hit their existing approval limit.

*Are the two transactions create listing and approve contract? Or is it approve listing and then transfer tokens for staking?*
First the seller would approve the marketplace contract to control their tokens (transaction 1), then they create their listing (transaction 2).

*Is it possible to do either one of these in a combined single step?*
It's not possible without a non-standard token contract. There used to be an openzeppelin contract that did it (ERC827), but it was removed for being insecure.

Note that this whole token approval process will also need to happen when we want to allow payments in ERC20 (eg DAI).

**Comment by cuongdo** [comment]
I think there are a lot of currently commonplace UX annoyances with DApps that won't be acceptable in the long-term.

That said, let's focus on what we can do better in the short-term. After further thought, I'm not convinced that approvals are sufficient. Consider the following events:

1. Seller acquires 50 OGN
2. Seller approves a 50 OGN allowance for the marketplace contract on wallet 1
3. Seller calls `OriginToken.transfer()`to transfer all 50 OGN to wallet 2
    * At this point, wallet 1 (the one that had the approval for 50 OGN) has no actual tokens in it
4. Buyer disputes
5. Arbitrator rules in buyer's favor
6. Seller's stake *should* be slashed, but **seller has no OGN balance** in wallet 1! So, `OriginToken.transferFrom()` fails due to insufficient balance.

Approvals are somewhat "soft" -- they don't guarantee that the money will be there in the future. I think that what we need is some sort of escrow for stakes. In step 2, instead of `approve`, we'd do a simple `transfer` to fund the escrow.

**Comment by nick** [comment]
Totally agree the UX is not optimal @matthewliu - though I think we can overcome it longer term with a mobile wallet solution, or possibly just managing a user's wallet, keys and ERC 20 balances ourself like Coinbase does.

@cuongdo we already have a kind of token escrow on the marketplace contract, in that the seller's tokens need to be transferred up front when creating a listing. Here's a modified example:

1. Seller acquires 50 OGN
2. Seller approves a 50 OGN allowance for the marketplace contract
3. Seller creates a listing with a 50 OGN stake. Those OGN are transferred to the Marketplace contract and are no longer under the seller's control.
4. Buyer makes offer, has offer accepted, then disputes
5. Arbitrator rules in buyer's favor
6. Seller's stake is slashed

The only way a seller could avoid this deposit slashing is to `withdraw` their listing before the buyer's dispute is ruled upon to get a refund of their OGN. To prevent that, we have the concept of the 'token arbitrator' who must be the one to withdraw a listing (although in v1 the token arbitrator will be the same as the seller).

**Comment by cuongdo** [comment]
@nick Thanks for clarifying. There’s a lot packed into the marketplace contract that I’m still digesting.

Option 2 does seem like the best short-term option.

**Comment by matthewliu** [comment]
Let's do option 2 and then figure out a better solution later. Thanks guys for calling this out.

**Comment by cuongdo** [comment]
@nick Let's consider this scenario:

1. Seller acquires 200 OGN
2. Seller approves a 200 OGN allowance for the marketplace contract
3. Seller creates a listing with a 50 OGN stake. 50 OGN are transferred to the Marketplace contract and are no longer under the seller's control. The other 150 OGN are still approved but remain in the seller's wallet.
4. Seller transfers 150 OGN elsewhere. Their wallet still has an approval for 150 OGN, but they have no OGN balance.

Just to confirm my understanding, **the seller would have to perform another approval for the stake amount (which requires a sufficient OGN balance) at this point?**

If so, performing a token migration without migrating approvals is no worse than this scenario, and we don't need to migrate approvals.

**Comment by nick** [comment]
To create another listing after step 4, the seller would **not** have to perform another approval. They'd just need to fund their wallet with sufficient OGN. An approved amount is only updated when `transferFrom` is called, or when the owner calls `increaseApproval` or `decreaseApproval`.

An approval can be more than the current balance... so it would also be possible for the seller to approve an infinite amount if they wanted to.

**Comment by cuongdo** [comment]
Yes, that makes sense. I'm closing this issue, because we've decided not to migrate approvals if/when we migrate token contracts.
