### ISSUE TITLE
Validate addresses of arbitrator, affiliate, messaging accounts 

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-js#541]
This is part of hardening origin-js.

At the origin-js layer, we should throw an error in the following scenarios:
 - ~set messaging account to anything else than official Origin messaging account~
 - create listing that uses non official Origin arbitrator or affiliate account
 - read a listing where arbitrator or affiliate is not official Origin account

**Comment by franckc** [comment]
@tyleryasaka we discussed the above during our security brainstorm this afternoon. Would you be ok adding some validation for this to origin-js ? Thank you sir !

**Comment by micahalcorn** [comment]
There is no concept of the messaging resource being aware or caring about who is generating what message. So I think it's the DApp's responsibility to indicate whether or not a messaging user is a trusted Origin account. If I'm right, then I'm not sure why Origin.js needs that value. I'll update @franck's original comment.

**Comment by micahalcorn** [comment]
I also think that @nick intended for the arbitrator on the listing to be the seller vs the arbitrator on the offer being the [Origin] centralized arbitrator in question.

Regardless, there is still a question of whether we hard-code the official Origin arbitrator and affiliate address in Origin.js for the time being or just let the DApp pass them in (from env vars) and go ahead and allow other DApps to potentially supply different values. cc @wanderingstan

**Comment by wanderingstan** [comment]
As for which layer has the hard-coded address, I say we go with whatever is the easiest for now. Either approach will need adjustments once we have other partners/developers building on our code, and we could use a few more thought cycles on where the right place is. (I idealistically lean toward it being the DApp, but recognize that security may tilt us towards origin.js package.)

**Comment by tyleryasaka** [comment]
Discussed with @franckc , these were the takeaways:
- @micahalcorn you are correct, the arbitrator on the listing is currently being set as the seller and this appears to be intentional. The arbitrator on the offer is the entity that will resolve disputes between the buyer and seller on an offer.
- We will pass in arbitrator and affiliate for offers as config options from the Dapp to origin-js. This allows them to be env vars in the Dapp that are passed in to origin-js at runtime, vs having to check in those addresses into source code.
- We will not do any verification when creating offers - there will be no params to specify these values when creating offers thus there will be nothing to validate. Additionally such validation would not add any security, as it can be trivially bypassed by interacting directly with the smart contracts. Instead, validation will occur upon retrieval of an offer, in the same way that our other offer validation is done. This protects us against people trying to bypass origin-js and sneak in a malicious arbitrator.

I'm going to work on this today and hopefully get most or all of it done. Changes should be trivial to implement. Will report back on my progress. FYI, tomorrow I'll be out of town so whatever doesn't get done today will need to be picked up by someone else.

**Comment by franckc** [comment]
CC @cuongdo since he is working on tightening up affiliate at marketplace contract level.

**Comment by wanderingstan** [comment]
@tyleryasaka writes: 

> ...the arbitrator on the listing is currently being set as the seller and this appears to be intentional. The arbitrator on the offer is the entity that will resolve disputes between the buyer and seller on an offer.

That doesn't sound right at all: Only the [_listing_ arbitrator](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L42) should be set to the buyer. This address decides who gets the OGN token. 

The [_offer_ arbitrator](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L52) decides disputes between buyer and seller and this should be set to an address Origin controls. 

I'm thinking we should rename these variables as its been pretty confusing. Prima facie, it sounds pretty ridiculous when you say that "the arbitrator is the seller".  The _listing arbitrator_ seems mis-named, as their only real powers are to decide whom gets how much OGN token after a sale. ([link](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L426-L434)) Maybe rename this to `depositArbitrator` or `depositManager`?
