### ISSUE TITLE
Store Attestations In IPFS

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin-js#609]
Per @joshfraser, let's store the Facebook, Twitter, and Airbnb IDs (or equivalent unique identifiers) in IPFS and include them in the API output so that the DApp can display and link to the verified profiles. For now, we will refrain from storing phone numbers and email addresses since we aren't prepared to hash and salt them and our identity implementation is a work in progress.

**Proposed Edit:**
Per @joshfraser we have decided to store Twitter and Airbnb ids to attestation `data` field in attestation claims so that the DApp can display and link to the verified profiles. For now, we will refrain from storing phone numbers and email addresses since we aren't prepared to hash and salt them and our identity implementation is a work in progress. Also we will not store any additional information from Facebook because of the privacy concerns. 

Pull Request: https://github.com/OriginProtocol/origin/pull/759

**Comment by franckc** [comment]
There are 3 components to this:
1. Modify bridge server to return IDs in attestation response
2. Modify origin-js to store those IDs in the user's profile data stored in IPFS.
3. Update DApp to show links to Fbook/Twitter/Airbnb profile's page for the user

**Comment by tomlinton** [comment]
I'm happy to take care of 1, it shouldn't be too hard since I've just been working on it. I'll raise an issue on `origin-bridge`.

**Comment by joshfraser** [comment]
4. We need to update the UI when people add these attestations to make it very obvious what you're doing.

**Comment by franckc** [comment]
I haven't checked the details, but for Facebook we might need the bridge server to actually return the profile URL rather than the ID. Reason is it may not be possible to construct a profile page url just based on ID ? We may have to call the Facebook graph API to get the profile URL, but then to do so an "App token" is needed. It would not be good to expose our "App token" in the DApp since anyone could then use it...

**Comment by joshfraser** [comment]
Not sure how reliable it is, but going to https://facebook.com/12703883 (my FB ID) redirects to https://www.facebook.com/joshfraser

**Comment by sparrowDom** [comment]
Just reading up on Facebook Graph Api changes:
- facebook user id is not exposed anymore
- a user id is generated that is unique for each combination of FB user / FB app. And that id as expected does not resolve to user's profile. (These things can be tested in [GraphAPI explorer](https://developers.facebook.com/tools/explorer/)
- it is possible to get a link, but that will only resolve if viewed by a friend of a user whose profile is being clicked

[Here](https://developers.facebook.com/docs/graph-api/reference/v2.2/user) is the api reference if anyone is interested. 

What we could get is user's name and picture. And store those two in IPFS. Anybody have better ideas?

**Comment by micahalcorn** [comment]
@sparrowDom what _do_ we get when the OAuth flow is completed?

**Comment by joshfraser** [comment]
Looks like they don't support that anymore due to abuse.

https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/

I've always liked the publicly auditable proofs approach. It's the way [Keybase](https://keybase.io/) does it and basically what we're using for the Airbnb integration. If we went with this approach, we'd give people a sentence to publicly post on their Facebook account like "Verifying myself on Origin as the owner of 0x123..." and then they would provide us with a link to that post that we can fetch and verify.

There are 3 benefits to doing it this way:

1. No one needs to trust Origin anymore since everyone can verify the link between the social account & Ethereum wallet for themselves.
2. It makes it far more obvious to the users that you're de-anonymizing yourself. Right now, users could easily (but inaccurately) assume that their data is private when it's not.
3. There's the possibility of a nice viral effect as people start posting these verification messages on their social channels. ([See this in action on Twitter w/ Keybase](https://twitter.com/search?q=verifying%20myself%3A%20I%20am%20&src=typd))

Downsides:

1. It's super geeky and most users aren't used to verifying themselves like this.

**Comment by sparrowDom** [comment]
@micahalcorn in the [first step](https://github.com/OriginProtocol/origin/blob/master/origin-bridge/logic/attestation_service.py#L315) on bridge server we receive the `access_token` which we then use to query [user information](https://developers.facebook.com/docs/graph-api/reference/v2.2/user).

@nick I like your idea with showing the number of friends a person has. Since that is IMHO a good indicator of not being fake. Personally I don't see a point why we wound need to match person's FB email and email attestation email (to verify they are not using a throw away email?). I would rather enforce the message that notifications are sent via email, to encourage people to use a real email. Also that would mean that email attestation is a precondition for FB attestation. Regarding FB account age from what I know is only guessable from the id, since user ids are auto incremented. And we would need another flow aside from FB's OAuth to get to that info (for example what @joshfraser recommends)

@joshfraser I like this approach since it is not limiting us in any way though I have a concern. I personally don't like my social accounts / real name to be publicly linked to my eth wallet. That is why I always delete the verification posts as soon as the 3rd party service verifies them. Is it possible other users will have reservations as well?

**Comment by nick** [comment]
@sparrowDom yea I'm thinking these attestations become much more valuable if we verify that data matches between services. Right now I can use a throwaway email, a throwaway SMS number and create throwaway profiles on Facebook, Twitter and Airbnb and still be 'fully verified' on Origin. 

Here's how we could match data:

1. Users sign up to Origin with Full Name and Email. Email is stored privately off-chain with Origin.
2. User verifies Facebook. Origin checks Name and Email matches those from step 1 and only provides attestation for each, eg 'Facebook name matches' and 'Facebook email matches'. Can also have extra attestations for, eg, 'Facebook account > 2 years old' and 'Facebook friends > 100'.
3. Same process for other services
4. Now the 'profile strength' is related to how many items match rather than just that they have accounts on those services. A profile with non-matching data can show a much lower strength.

Regarding publicly auditable proofs - I do like the technical side of it, I'm just not sure whether real world users would be comfortable posting stuff publicly on their profile. Personally I don't like it and always delete those posts straight after being verified. I know that defeats the purpose but I've never used a service where I had to keep that info up long term.

**Comment by sparrowDom** [comment]
So I guess the main question here is where do we draw the line. Looking at random Airbnb host's [publicly available information](https://www.airbnb.com/users/show/6182888). I can only see if a user has verified Email, Phone, Facebook, Government ID & Google+. No additional information on those attestations is available. 
<img width="1104" alt="screenshot 2018-10-12 15 05 10" src="https://user-images.githubusercontent.com/579910/46954066-e2df8400-d08f-11e8-8c03-70cf6fe44761.png">

Also Airbnb [states in documentation](https://www.airbnb.com/help/article/1237/how-does-it-work-when-airbnb-asks-for-an-id) that your host receives:

- The first name on your ID
- Whether you’re over or under 25 years old
- Whether your ID has been successfully added
- Your profile photo and profile name

So outside of what a user fills out inside an Airbnb profile, Airbnb exposes approximate age range + first name on ID. 

There is also one more important distinction between us and sites like Airbnb, by default we (need to) expose user's wallet address. So all the PII attached to users profile is also attached to users wallet. 

Personally I wouldn't have a problem exposing that information to users that are in a buy/sell relationship with me. Since I will be transacting with those users, I am fine with having a more intimate relationship with them and exposing more of my private information. But linking my FB profile/email/twitter to my (primary ethereum) wallet publicly is something I wouldn't be comfortable with. I can't think of any site exposing their users email or phone number publicly. 

I agree with Josh in whatever we do, we should be transparent to our users al let them know what they are doing and what are the consequences. But personally I wouldn't pin that kind of information to my ethereum wallet. 

Just my 2 cents....

**Comment by joshfraser** [comment]
The checkmark works on Airbnb because they're a trusted intermediary if you ever need that information. A checkmark showing the existence of an email address is worthless information unless there's some path to seeing the raw data. The problem is we don't want to be the intermediary and holding PII is more of a liability than an asset.

One solution here is to verify data, sign an attestation and then throw away the original data. This is the approach that Civic and uPort are advocating, which works well for private data that is only shared by the owner upon request. For example, we could verify your mailing address, then throw away the data. But you could still provide the raw data upon request and counterparties could verify that the data matches based on the signatures.

As far as deanonymizing your Ethereum wallet, we should strongly encourage users to create a new wallet instead of attaching their identities to existing wallets with historical transactions.

**Comment by franckc** [comment]
@matthewliu @joshfraser: Domen started implementing saving Twitter and Airbnb user ids to IPFS but he needs product requirements for what to do for Facebook. What shall we decide on that ?

**Comment by sparrowDom** [comment]
Thanks for posting this from Discord @micahalcorn. I prepared a solution where twitter/airbnb platform ids are stored in the ERC725 claim in the `data` field. It is not "human readable" and is hex encoded but should be more resilient then storing IPFS address to claim's `data` field and fetching the information from IPFS. Is there any reason I might have missed why we would prefer having this in IPFS?

**Comment by micahalcorn** [comment]
I think that we generally try to store as much data as possible off-chain to reduce costs. But I don't know how this data fits into the identity standard that we're currently using. @tyleryasaka, do you have a preference here, knowing that we may end up with a different identity implementation?

**Comment by sparrowDom** [comment]
From reading [ERC735](https://github.com/ethereum/EIPs/issues/735) the values of `data` field are not really strongly defined. They can be anything that is required for that topic. For profile information we use that field to store IPFS hash, so that we can read the remainder of the data from IPFS. Which makes sense, since there is picture information in there. 

As it stands currently IPFS hash takes up 32 bytes and Airbnb & Twitter ids take up from 28+ bytes. Depending on the length of the airbnbId / twitter screen name. I wouldn't be worried this will influence gas costs in a bad way.

**Comment by tyleryasaka** [comment]
@sparrowDom We should not be storing PII on-chain, as that data is irrevocable. I am still very nervous about IPFS but at least it's theoretically possible for IPFS data to be unpinned.

It's correct that ERC735 doesn't specify the format of claims. Regardless of which standard Origin ultimately uses, further standardization of the claims format is needed for the claims to be useful across other platforms.

**Comment by sparrowDom** [comment]
Solved via: https://github.com/OriginProtocol/origin/pull/759
