### ISSUE TITLE
UI: Show buyer timeout information

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/origin-js#71]
When a `Purchase` is in a BUYER_PENDING stage, after 21 days it automatically moves over.

We'll need to show where this countdown is in the UI when it is active, probably on the purchase detail page and My Listings page.

Do we want to show this only to the buyer and seller? 

- [x] Add a `Purchase.get` method to origin.js, which includes timeout
- [ ] Add UI element to purchase detail
- [ ] Add UI element to my listings

**Comment by wanderingstan** [comment]
Minor comment: We should consider a more descriptive name for `BUYER_PENDING`. Coming back to this after a week a way I can't remember what this means. E.g. are we waiting for a buyer at all? Are we waiting for the buyer to pay?

**Comment by micahalcorn** [comment]
I like the `awaiting_{event}` convention, which might be implied by `AWAITING_PAYMENT`. This issue makes me realize that design and engineering may not be entirely on the same page regarding the steps involved in a transaction.

_At the risk of this being the wrong place for this..._

In the current UI, there are six events that affect transaction state, each caused by the action of a **sole party**, and two of them (5 & 6) being potentionally out of sequence:

1) Create listing (**seller**)
2) Buy listing (**buyer**) - presumed to be the equivalent of sending money
3) Fulfill order (**seller**)
4) Receive order (**buyer**)
5) Withdraw funds (**seller**)
6) Provide feedback (**buyer**)

We don't currently handle disputes as a potential part of the flow, and the seller's feedback (applicable to the buyer) is not currently handled. The current philosophy is that there is a distinction between the contexts of a buyer's review and a seller's review. The buyer is reviewing the **_listing_** - not reviewing the seller. And the seller is reviewing the buyer - not the purchase or some other instance.

**Comment by micahalcorn** [comment]
@DanielVF that makes sense if review/feedback is required. That would beg the question what constitutes a valid review. 😬

**Comment by DanielVF** [comment]
Well, the reviews are optional - we're just including them in with the steps that the buyer and seller are already doing. As a first pass, I was thinking 1-5 star and optional text.

**Comment by micahalcorn** [comment]
Since we [don't currently plan to use a reasonably short buyer timeout](https://github.com/OriginProtocol/origin-js/issues/365#issuecomment-418532841), we will skip this for now.
